export enum RootPath {
  Home = '/',
  Login = '/dang-nhap',
  Register = '/dang-ky-tai-khoan',
  ForgotPassword = '/quen-mat-khau',
  ChangePassword = '/mat-khau-moi',
  Cart = '/gio-hang',
  Payment = '/gio-hang/payment',
  Search = '/tim-kiem',
  ProductList = '/danh-sach-san-pham',
  ProductDetails = '/chi-tiet-san-pham',
  Profile = '/ho-so',
  Order = '/don-hang',
  Brand = '/thuong-hieu',
}

export enum ApiTags {
  Auth = '/auth',
  Brand = '/brands',
  Profile = '/profile',
  Images = '/images',
  Products = '/products',
  Categories = '/categories',
  Attributes = '/attributes',
  Address = '/address',
  OrdersMnt = '/orders-mnt',
  Users = '/users',
  Notifications = '/notifications',
  Cart = '/carts',
  Order = '/orders',
}
