export enum RootPath {
  Home = '/',
  Login = '/dang-nhap',
  Register = '/dang-ky-tai-khoan',
  ForgotPassword = '/quen-mat-khau',
  ChangePassword = '/mat-khau-moi',
  Cart = '/gio-hang',
  Payment = '/thanh-toan',
  Search = '/tim-kiem',
  ProductList = '/danh-sach-san-pham',
  ProductDetails = '/chi-tiet-san-pham',
  Profile = '/ho-so',
  Order = '/danh-sach-don-hang',
  AllOrder = '/danh-sach-don-hang/tat-ca',
  Processing = '/danh-sach-don-hang/dang-xu-ly',
  WaitForPay = '/danh-sach-don-hang/cho-thanh-toan',
  Transport = '/danh-sach-don-hang/van-chuyen',
  Complete = '/danh-sach-don-hang/hoan-thanh',
  Cancelled = '/danh-sach-don-hang/da-huy',
  OrderDetails= '/chi-tiet-don-hang',
  Brand = '/thuong-hieu',
}

export enum ApiTags {
  Auth = '/auth',
  Brand = '/brands',
  Profile = '/profile',
  Images = '/images',
  Products = '/products',
  Categories = '/categories',
  Attributes = '/attributes',
  Address = '/address',
  OrdersMnt = '/orders-mnt',
  Users = '/users',
  Notifications = '/notifications',
  Cart = '/carts',
  Order = '/orders',
}
